### ISSUE TITLE
Some dependencies missing?

### ISSUE THREAD

**Issue by mthld** [clic-2000/sebastien-bertholom.fr#2]
Hi,

I tried to run it on my laptop but some stuff seems missing from the repo. I did the following to set it up:
```
$ mkdir assets/css
$ sassc assets/sass/style.scss assets/css/style.css
```

But still there is this line in the code:
```
<link rel="stylesheet" href="assets/css/bulma/bulma.min.css">
```

And the `css` directory don't have it:
```
$ ls -lah assets/css/
Permissions Size User Date Modified Name
.rw-r--r--  2.2k m_b  30 Aug 10:41  style.css
```

Thanks for your help!

**Comment by myrdinm** [comment]
Hello,

I added an exception in ``.gitignore`` (https://github.com/clic-2000/sebastien-bertholom.fr/commit/d69efdc71de9220b26eb8096447a62761eb99ac4) for the subfolder with the dependency, it should be okay now.

**Comment by mthld** [comment]
Yeepee, fixed it!
